[build]
  # Tell Netlify the code lives in the client subfolder
  base = "client"
  
  # Netlify automatically runs npm install inside base ('client')
  command = "npm run build"
  
  # Relative to the base directory ('client/dist')
  publish = "dist"

# Redirects all traffic to index.html for Single Page Application (SPA) routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
