[build]
  # Force Netlify to install dependencies before building
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
      Cross-Origin-Embedder-Policy = "unsafe-none"
      Cross-Origin-Opener-Policy = "same-origin-allow-popups"
